### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by RiversideRocks** [onyxcode/xdash#1]
This looks quite neat, do you have a demo up?

**Comment by creepinson** [comment]
There isn't one yet but I made a prhere  to include instructions on how to set it up yourself: #4

**Comment by creepinson** [comment]
Alright, I created a demo 
https://xdash-demo.herokuapp.com/

the auth logic doesn't work yet because the api url can't be changed but if that is fixed then I can fix that
What does work is the css and js so you can still see what it looks like
