### ISSUE TITLE
Use API_URL environment variable along with templates 

### ISSUE THREAD

**Issue by creepinson** [onyxcode/xdash#3]
Can we use an API_URL env variable to define where the py auth api is located? eg. (`API_URL=http://localhost:6969`) and default to localhost:6969 when it is not defined manually?

**Comment by onyxcode** [comment]
hmm good idea

**Comment by creepinson** [comment]
Might have to use templates and not html tho

**Comment by creepinson** [comment]
I havent posted an update to this but I will try to keep working on this toay
